version: '2.4'
services:
    db:
        image: mariadb:latest
        hostname: db
        ports:
          - "13306:3306"
        volumes:
          - ./db/data:/var/lib/mysql
          - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: arthur
        healthcheck:
          test: mysqladmin -uroot -parthur ping
          interval: 2s
          timeout: 5s
          retries: 30
    lottery-management:
        image: chengkerossli/lottery-management:latest
        hostname: lottery-management
        depends_on:
          db:
            condition: service_healthy
        ports:
          - "8080:8080"
        environment:
          DB_HOST: db:3306
    lottery-admin-app:
        image: chengkerossli/lottery-admin-app:latest
        hostname: lottery-admin-app
        depends_on:
          - lottery-management
        ports:
          - "18080:8080"
        environment:
          BACKEND_HOST: 139.180.190.100:8080
        
